name: TraqClone

options:
  bundleIdPrefix: net.ras0q
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false

settingGroups:
  commonSettings:
    base:
      CURRENT_PROJECT_VERSION: '1'
      MARKETING_VERSION: '1.0'
      GENERATE_INFOPLIST_FILE: 'YES'
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
      INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'

targets:
  TraqClone:
    type: application
    platform: iOS
    sources:
      - App
      - Modules
      - project.yml
      - README.md
    dependencies:
      - package: Root
    preBuildScripts:
      - name: Run Formatter
        script: /opt/homebrew/bin/swiftformat .
      - name: Run Linter
        script: /opt/homebrew/bin/swiftlint .
    settings:
      base:
        DEVELOPMENT_ASSET_PATHS: '"App/Preview Content"'
      groups:
        - commonSettings
  TraqCloneTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TraqCloneTests
    dependencies:
      - target: TraqClone
    settings:
      groups:
        - commonSettings
  TraqCloneUITests:
    platform: iOS
    type: bundle.ui-testing
    sources:
      - TraqCloneUITests
    dependencies:
      - target: TraqClone
    platform: iOS
    settings:
      groups:
        - commonSettings

packages:
  Activity:
    path: ./Views/Activity
    group: ./Views
  Channel:
    path: ./Views/Channel
    group: ./Views
  Clip:
    path: ./Views/Clip
    group: ./Views
  Home:
    path: ./Views/Home
    group: ./Views
  Root:
    path: ./Views/Root
    group: ./Views
  User:
    path: ./Views/User
    group: ./Views
